<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <NoWarn>$(NoWarn);NETSDK1057;CS0114;CS0108;CS0162</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.*" ExcludeAssets="runtime" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="StoreApi">
      <HintPath>lib\StoreApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="CS2MenuManager">
      <HintPath>lib\CS2MenuManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
